{"content": "\nLet's examine the following code:\n\n\n\n\n\nCode section 6.7: Handling exceptions.\n 1 public void methodA() throws SomeException {\n 2     // Method body\n 3 }\n 4 \n 5 public void methodB() throws CustomException, AnotherException {\n 6     // Method body\n 7 }\n 8 \n 9 public void methodC() {\n10     methodB();\n11     methodA();\n12 }\n\n\nIn the code section 6.7, methodC is invalid.  Because methodA and methodB pass (or throw) exceptions, methodC must be prepared to handle them.  This can be handled in two ways: a try-catch block, which will handle the exception within the method and a throws clause which would in turn throw the exception to the caller to handle.  The above example will cause a compilation error, as Java is very strict about exception handling. So the programmer is forced to handle any possible error condition at some point.\n\nA method can do two things with an exception: ask the calling method to handle it by the throws declaration or handle the exception inside the method by the try-catch block.\n\nTo work correctly, the original code can be modified in multiple ways.  For example, the following:\n\n\n\n\n\nCode section 6.8: Catching and throwing exceptions.\n1 public void methodC() throws CustomException, SomeException {\n2   try {\n3     methodB();\n4   } catch(AnotherException e) {\n5     // Handle caught exceptions.\n6   }\n7   methodA();\n8 }\n\n\nThe AnotherException from methodB will be handled locally, while CustomException and SomeException will be thrown to the caller to handle it. Most of the developers are embarrassed when they have to choose between the two options. This type of decision should not be taken at development time. If you are a development team, it should be discussed between all the developers in order to have a common exception handling policy.\n", "heading": "Example of handling exceptions"}