{"content": "\nA throw statement exits from a method and so on and so on or it is caught by a try/catch block. It does not return a variable but an exception:\n\n\n\n\n\nCode section 3.20: A return statement.\n1     public int getAge() {\n2         throw new NullPointerException();\n3     }\n\n\nBeware not to write statements after a throw statement which would not be executed too! Each throw statement is ended by a semi-colon (;).\n", "heading": "Throw statement"}