{"content": "\nthrow is a keyword; it 'throws' an exception. In a throw statement, the three types of objects that can be thrown are: Exception, java:Throwable, and java:Error\n\nthrow <Exception Ref>;\n\n\n\n\n\n\npublic Customer findCustomer( String name ) throws '''CustomerNotFoundException'''\n {\n    Customer custRet = null;\n \n    Iterator iter = _customerList.iterator();\n    while ( iter.hasNext() )\n    {\n        Customer cust = (Customer) iter.next();\n        if ( cust.getName().equals( name ) )\n        {\n           // --- Customer find --\n           custRet = cust;\n           break;\n        }\n     }\n     if ( custRet == null )\n     {\n        // --- Customer not found ---\n        throw new '''CustomerNotFoundException'''( \"Customer \"+ name + \" was not found\" );\n     }\n \n    return custRet\n  }\n\n", "heading": "throw"}